name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./output

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-artifact
        path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: app-artifact
        path: ./output

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Lis채채 t채m채 secret GitHub-repossa (Azure SPN JSON)

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: your-azure-webapp-name  # Azure Web App -nimesi
        package: ./output